version: "3.5"
services:
  redis_db:
    container_name: minivalist-redis
    image: redis
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - nginx-network
  db:
    container_name: minivalist-db
    image: "postgres:11"
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - valista_database:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - nginx-network
  etl:
    container_name: minivalist-etl
    build: ./etl
    image: minivalist-etl
    volumes:
      - .env:/usr/app/.env
      - ./etl/package.json:/usr/app/package.json
      - ./etl/bin:/usr/app/bin
      - ./etl/node_modules:/usr/app/node_modules
    command: yarn run dev-vs
    depends_on:
      - db
    networks:
      - nginx-network
  api:
    container_name: minivalist-api
    build: ./api
    image: minivalist-api
    ports:
      - "4000:4000"
    volumes:
      - .env:/usr/app/.env
      - ./api/schema:/usr/app/schema
      - ./api/node_modules:/usr/app/node_modules
    command: node index.js
    depends_on:
      - db
    links:
      - redis_db
    networks:
      - nginx-network
  web:
    container_name: minivalist-web
    env_file: ./.env
    build: ./web
    image: minivalist-web
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - nginx-network

volumes:
  redis-data:
    driver: local
  valista_database:
    external: true

networks:
  nginx-network:
    name: nginx-network
